Bogor/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls')),
]

shop/urls.py
from django.urls import path, include
from . import views
from . import adminviews
from django.conf import settings
from django.conf.urls.static import static

app_name = 'shop'

urlpatterns = [
    path('', views.index, name='index'),
    path('puokste/', views.flower, name='flowers'),
    path('dekoracijos/', views.decoration, name='decorations'),
    path('dekoracija/<int:deco_type_id>/', views.product_detail, name='product_detail'),
    path('duk/', views.faq, name='faq'),
    path('Kontaktai/', views.contact_view, name='contact'),
    path('pristatymas/', views.delivery, name='shipping'),
    path('krepselis/', views.cart_view, name='cart'),
    path('krepselis/prideti/', views.add_to_cart, name='add_to_cart'),
    path('krepselis/atnaujinti/', views.update_cart, name='update_cart'),
    path('prekselis/pasalinti/<int:item_id>/', views.remove_from_cart, name='remove_from_cart'),
    path('krepselis/isvalyti/', views.clear_cart, name='clear_cart'),
    path('atsiskaitymas/', views.checkout_view, name='checkout'),
    path('uzsakymas/<int:order_id>/', views.checkout_complete_view, name='checkout_complete'),

    ### Admin ###
    path('adminas/', adminviews.admin_login, name='admin_login'),
    path('adminas/dashboard', adminviews.admin_dashboard, name='admin_dashboard'),
    path('adminas/products', adminviews.admin_products, name='admin_products'),
    path('adminas/products/flowers', adminviews.admin_products_flowers, name='admin_products_flowers'),
    path('adminas/products/decorations', adminviews.admin_products_decorations, name='admin_products_decorations'),
    path('adminas/products/decoration/<int:decoration_id>/', adminviews.get_decoration, name='get_decoration'),
    path('adminas/products/decorationtype/<int:type_id>/', adminviews.get_decoration_type, name='get_decoration_type'),
    path('adminas/products/decorationtype/delete/<int:type_id>/', adminviews.delete_decoration_type, name='delete_decoration_type'),
    path('adminas/products/decoration/delete/<int:decoration_id>/', adminviews.delete_decoration, name='delete_decoration'),
    path('adminas/products/wrappingpaper', adminviews.admin_products_wrapping_paper, name='admin_products_wrapping_paper'),
    path('adminas/products/wrappingpaper/<int:wrapping_paper_id>/', adminviews.get_wrapping_paper, name='get_wrapping_paper'),
    path('adminas/orders', adminviews.admin_orders, name='admin_orders'),
    path('adminas/order/<int:order_id>/', adminviews.admin_order_detail, name='admin_order_detail'),
    path('adminas/inventory', adminviews.admin_inventory, name='admin_inventory'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/components/footer.html
<div class="flex-grow gap-3">
    <ul class="text-center">
        <li class="mb-4"><a href="{% url 'shop:faq' %}" class="hover:underline hover:text-gray-300">D.U.K</a></li>
        <li class="mb-4"><a href="{% url 'shop:contact' %}" class="hover:underline hover:text-gray-300">Kontaktai</a></li>
        <li class="mb-8"><a href="{% url 'shop:shipping' %}" class="hover:underline hover:text-gray-300">Pristatymo sąlygos</a></li>
    </ul>
    <p>&copy; 2024 Bogor.lt</p>
</div>

templates/components/header.html
<div>
    <div class="relative flex items-center justify-between h-16">
        <button id="menu-button" class="absolute left-4 bg-[#8f6d75] text-white p-4 text-xl rounded hover:bg-[#734f59]" onclick="toggleMenu()">☰ Menu</button>
        <a href="{% url 'shop:index' %}" class="text-3xl font-bold mx-auto">Bogor</a>
        <a href="{% url 'shop:cart' %}" class="absolute right-4 bg-[#8f6d75] text-white p-4 text-xl rounded hover:bg-[#734f59]">
            <i class="bi bi-cart"></i></a>
    </div>
    <div id="sidebar" class="fixed top-0 left-0 h-full bg-[#8f6d75] text-white p-4 transform border-r-4 border-[#734f59] -translate-x-full transition-transform duration-300" style="width: 200px;">
        <button class="font-bold mb-4 cursor-pointer bg-transparent border-none p-4 text-xl rounded hover:bg-[#734f59]" onclick="toggleMenu()">☰ Menu</button>

        <ul class="space-y-4">
            <li><a href="{% url 'shop:index' %}" class="block hover:bg-[#734f59] rounded p-2">Pagrindinis</a></li>
            <li><a href="{% url 'shop:flowers' %}" class="block hover:bg-[#734f59] rounded p-2">Puokštės</a></li>
            <li><a href="{% url 'shop:decorations' %}" class="block hover:bg-[#734f59] rounded p-2">Dekoracijos</a></li>
            <li><a href="#" class="block hover:bg-[#734f59] rounded p-2">Papuošalai</a></li>
        </ul>
    </div>
</div>